### ISSUE TITLE
Shopware 5.7.11 compatibility?

### ISSUE THREAD

**Issue by cgpro** [Nets-eCom/shopware5-easy-checkout#2]
Hi,

after upgrading to SW 5.7.11 I get the following error in the php error log and a payment is not possible:

2022/05/12 12:42:29 [error] 19024#19024: *59263 FastCGI sent in stderr: "PHP message: PHP Warning:  The use statement with non-compound name 'Shopware' has no effect in /var/www/clients/client1/web2/web/custom/plugins/NetsCheckoutPayment/Controllers/Frontend/NetsCheckout.php on line 7" while reading response header from upstream, client: 178.26.xxx.238, server: [stage.myshopurl.de](http://stage.myshopurl.de/), request: "GET /NetsCheckout HTTP/2.0", upstream: "[fastcgi://unix:/var/lib/php5-fpm/web2.sock:](fastcgi://unix/var/lib/php5-fpm/web2.sock:)", host: "[stage.myshopurl.de](http://stage.myshopurl.de/)", referrer: "https://stage.myshopurl.de/checkout"

The PHP version set is definitely 7.4.
Shopware-Version 5.7.11 (latest security release)
Nets Checkout Payment 1.1.1.
Server NGINX with PHP-FPM

**Comment by Tim-Badin** [comment]
Hi @cgpro 
Thank you for notice. 
We are reviewing our case. Our deveopers have identified the root cause and you will be contacted by our customer team to provide SSH/FTP access via separate email.
Kind regards

**Comment by cgpro** [comment]
By when can we expect to be contacted?

**Comment by cgpro** [comment]
Works like a charm. 👍
